import { ProjectConfig } from '../types';

// ─── ENV TEMPLATE ───────────────────────────────────────────────────────────
export function getEnvTemplate(config: ProjectConfig): string {
  const { database, features, projectName, deployTarget } = config;
  let env = `# ${projectName} Environment Variables\n# Generated by Navi 🧭\n\n# App\nNODE_ENV=development\nPORT=5000\nCLIENT_URL=http://localhost:3000\n\n`;

  if (features.includes('JWT Authentication')) env += `# JWT\nJWT_SECRET=your_super_secret_key_change_this_in_production\nJWT_EXPIRES_IN=7d\n\n`;
  if (features.includes('OAuth (Google/GitHub)')) env += `# OAuth\nGOOGLE_CLIENT_ID=your_google_client_id\nGOOGLE_CLIENT_SECRET=your_google_client_secret\nGITHUB_CLIENT_ID=your_github_client_id\nGITHUB_CLIENT_SECRET=your_github_client_secret\nSESSION_SECRET=your_session_secret\n\n`;
  if (database === 'MongoDB') env += `# MongoDB\nMONGODB_URI=mongodb://localhost:27017/${projectName.toLowerCase()}\n\n`;
  if (database === 'PostgreSQL') env += `# PostgreSQL\nDATABASE_URL=postgresql://username:password@localhost:5432/${projectName.toLowerCase()}\n\n`;
  if (database === 'MySQL') env += `# MySQL\nDATABASE_URL=mysql://username:password@localhost:3306/${projectName.toLowerCase()}\n\n`;
  if (database === 'SQLite') env += `# SQLite\nDATABASE_URL=file:./dev.db\n\n`;
  if (database === 'Firebase Firestore') env += `# Firebase\nFIREBASE_PROJECT_ID=your_project_id\nFIREBASE_CLIENT_EMAIL=your_client_email\nFIREBASE_PRIVATE_KEY=your_private_key\n\n`;
  if (database === 'Supabase') env += `# Supabase\nSUPABASE_URL=https://your-project.supabase.co\nSUPABASE_SERVICE_KEY=your_service_key\nSUPABASE_ANON_KEY=your_anon_key\n\n`;
  if (features.includes('Payment Gateway (Razorpay)')) env += `# Razorpay\nRAZORPAY_KEY_ID=your_key_id\nRAZORPAY_KEY_SECRET=your_key_secret\n\n`;
  if (features.includes('Payment Gateway (Stripe)')) env += `# Stripe\nSTRIPE_SECRET_KEY=sk_test_your_key\nSTRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret\n\n`;
  if (features.includes('Email Service (Nodemailer)')) env += `# Email (Nodemailer)\nSMTP_HOST=smtp.gmail.com\nSMTP_PORT=587\nSMTP_USER=your_email@gmail.com\nSMTP_PASS=your_app_password\n\n`;
  if (features.includes('SMS Service (Twilio)')) env += `# Twilio\nTWILIO_ACCOUNT_SID=your_account_sid\nTWILIO_AUTH_TOKEN=your_auth_token\nTWILIO_PHONE_NUMBER=+1234567890\n\n`;
  if (features.includes('Caching (Redis)') || features.includes('Background Jobs (BullMQ)')) env += `# Redis\nREDIS_URL=redis://localhost:6379\nREDIS_HOST=localhost\nREDIS_PORT=6379\nREDIS_PASSWORD=\n\n`;
  if (features.includes('Search (Elasticsearch)')) env += `# Elasticsearch\nELASTICSEARCH_URL=http://localhost:9200\nELASTICSEARCH_USERNAME=elastic\nELASTICSEARCH_PASSWORD=your_password\n\n`;
  if (features.includes('Error Tracking (Sentry)')) env += `# Sentry\nSENTRY_DSN=https://your_sentry_dsn\n\n`;
  if (features.includes('Push Notifications (Web Push)')) env += `# Web Push (VAPID)\nVAPID_PUBLIC_KEY=your_vapid_public_key\nVAPID_PRIVATE_KEY=your_vapid_private_key\nVAPID_EMAIL=mailto:your@email.com\n\n`;
  if (deployTarget === 'Vercel') env += `# Vercel\nVERCEL_TOKEN=your_vercel_token\n\n`;
  if (deployTarget === 'Netlify') env += `# Netlify\nNETLIFY_AUTH_TOKEN=your_netlify_token\nNETLIFY_SITE_ID=your_site_id\n\n`;
  if (features.includes('Cloud Storage (AWS S3)')) env += `# AWS S3\nAWS_REGION=us-east-1\nAWS_ACCESS_KEY_ID=your_access_key\nAWS_SECRET_ACCESS_KEY=your_secret_key\nAWS_S3_BUCKET=your_bucket_name\n\n`;

  return env;
}

// ─── ESLINT + PRETTIER ───────────────────────────────────────────────────────
export function getEslintConfig(config: ProjectConfig): string {
  const isTs = config.frontendLanguage === 'typescript';
  return JSON.stringify({
    env: { browser: true, es2020: true, node: true },
    extends: [
      'eslint:recommended',
      ...(isTs ? ['@typescript-eslint/recommended'] : []),
      ...(config.frontendFramework.includes('React') ? ['plugin:react/recommended', 'plugin:react-hooks/recommended'] : []),
      'prettier'
    ],
    parser: isTs ? '@typescript-eslint/parser' : undefined,
    plugins: [
      ...(isTs ? ['@typescript-eslint'] : []),
      ...(config.frontendFramework.includes('React') ? ['react', 'react-hooks'] : [])
    ],
    rules: {
      'no-console': 'warn',
      'no-unused-vars': isTs ? 'off' : 'warn',
      ...(isTs ? { '@typescript-eslint/no-unused-vars': 'warn', '@typescript-eslint/no-explicit-any': 'warn' } : {}),
      ...(config.frontendFramework.includes('React') ? { 'react/react-in-jsx-scope': 'off', 'react/prop-types': 'off' } : {})
    },
    settings: config.frontendFramework.includes('React') ? { react: { version: 'detect' } } : {}
  }, null, 2);
}

export function getPrettierConfig(): string {
  return JSON.stringify({
    semi: true,
    singleQuote: true,
    tabWidth: 2,
    trailingComma: 'es5',
    printWidth: 100,
    bracketSpacing: true,
    arrowParens: 'avoid',
    endOfLine: 'lf'
  }, null, 2);
}

export function getEslintIgnore(): string {
  return `node_modules\ndist\nout\nbuild\n.env\ncoverage\n`;
}

// ─── VERCEL / NETLIFY CONFIG ─────────────────────────────────────────────────
export function getVercelConfig(config: ProjectConfig): string {
  const isFullStack = config.frontendFramework !== 'None (Backend only)' && config.backendFramework !== 'None (Frontend only)';
  return JSON.stringify({
    version: 2,
    builds: isFullStack ? [
      { src: 'frontend/package.json', use: '@vercel/static-build', config: { distDir: 'dist' } },
      { src: 'backend/src/server.ts', use: '@vercel/node' }
    ] : [
      { src: 'src/server.ts', use: '@vercel/node' }
    ],
    routes: isFullStack ? [
      { src: '/api/(.*)', dest: 'backend/src/server.ts' },
      { src: '/(.*)', dest: 'frontend/$1' }
    ] : [
      { src: '/(.*)', dest: 'src/server.ts' }
    ]
  }, null, 2);
}

export function getNetlifyConfig(config: ProjectConfig): string {
  const isFullStack = config.frontendFramework !== 'None (Backend only)';
  return `[build]
  ${isFullStack ? 'base = "frontend"\n  publish = "dist"\n  command = "npm run build"' : 'publish = "dist"\n  command = "npm run build"'}

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 3000
`;
}

export function getRailwayConfig(config: ProjectConfig): string {
  return `[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
`;
}

// ─── SMS SERVICE ─────────────────────────────────────────────────────────────
export function getSmsService(): string {
  return `import twilio from 'twilio';

const client = twilio(
  process.env.TWILIO_ACCOUNT_SID!,
  process.env.TWILIO_AUTH_TOKEN!
);

export const sendSms = async (to: string, body: string): Promise<void> => {
  await client.messages.create({
    body,
    from: process.env.TWILIO_PHONE_NUMBER!,
    to,
  });
};

export const sendOtp = async (to: string): Promise<string> => {
  const otp = Math.floor(100000 + Math.random() * 900000).toString();
  await sendSms(to, \`Your OTP is: \${otp}. Valid for 10 minutes.\`);
  return otp;
};

export const sendWelcomeSms = async (to: string, name: string): Promise<void> => {
  await sendSms(to, \`Welcome to our platform, \${name}! 🎉\`);
};
`;
}

// ─── REDIS CACHING SERVICE ───────────────────────────────────────────────────
export function getRedisService(): string {
  return `import Redis from 'ioredis';

const redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379', {
  password: process.env.REDIS_PASSWORD || undefined,
  retryDelayOnFailover: 100,
  maxRetriesPerRequest: 3,
});

redis.on('connect', () => console.log('✅ Redis connected'));
redis.on('error', (err) => console.error('❌ Redis error:', err));

export const cache = {
  // Set with expiry (seconds)
  set: async (key: string, value: any, ttlSeconds = 3600): Promise<void> => {
    await redis.set(key, JSON.stringify(value), 'EX', ttlSeconds);
  },

  get: async <T>(key: string): Promise<T | null> => {
    const data = await redis.get(key);
    return data ? JSON.parse(data) : null;
  },

  delete: async (key: string): Promise<void> => {
    await redis.del(key);
  },

  deletePattern: async (pattern: string): Promise<void> => {
    const keys = await redis.keys(pattern);
    if (keys.length > 0) await redis.del(...keys);
  },

  exists: async (key: string): Promise<boolean> => {
    const result = await redis.exists(key);
    return result === 1;
  },

  // Cache-aside pattern helper
  getOrSet: async <T>(key: string, fetchFn: () => Promise<T>, ttl = 3600): Promise<T> => {
    const cached = await cache.get<T>(key);
    if (cached) return cached;
    const fresh = await fetchFn();
    await cache.set(key, fresh, ttl);
    return fresh;
  },
};

export const cacheMiddleware = (ttl = 300) => async (req: any, res: any, next: any) => {
  const key = \`cache:\${req.originalUrl}\`;
  const cached = await cache.get(key);
  if (cached) return res.json(cached);

  const originalJson = res.json.bind(res);
  res.json = async (data: any) => {
    await cache.set(key, data, ttl);
    return originalJson(data);
  };
  next();
};

export default redis;
`;
}

// ─── OAUTH ───────────────────────────────────────────────────────────────────
export function getOauthConfig(): string {
  return `import passport from 'passport';
import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
import { Strategy as GitHubStrategy } from 'passport-github2';
import User from '../models/user.model';

passport.use(new GoogleStrategy({
  clientID: process.env.GOOGLE_CLIENT_ID!,
  clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
  callbackURL: '/api/auth/google/callback',
}, async (accessToken, refreshToken, profile, done) => {
  try {
    let user = await (User as any).findOne({ oauthId: profile.id, oauthProvider: 'google' });
    if (!user) {
      user = await (User as any).create({
        name: profile.displayName,
        email: profile.emails?.[0]?.value,
        oauthId: profile.id,
        oauthProvider: 'google',
        avatar: profile.photos?.[0]?.value,
        isVerified: true,
      });
    }
    done(null, user);
  } catch (err) {
    done(err);
  }
}));

passport.use(new GitHubStrategy({
  clientID: process.env.GITHUB_CLIENT_ID!,
  clientSecret: process.env.GITHUB_CLIENT_SECRET!,
  callbackURL: '/api/auth/github/callback',
}, async (accessToken: string, refreshToken: string, profile: any, done: any) => {
  try {
    let user = await (User as any).findOne({ oauthId: profile.id, oauthProvider: 'github' });
    if (!user) {
      user = await (User as any).create({
        name: profile.displayName || profile.username,
        email: profile.emails?.[0]?.value || \`\${profile.username}@github.com\`,
        oauthId: profile.id,
        oauthProvider: 'github',
        avatar: profile.photos?.[0]?.value,
        isVerified: true,
      });
    }
    done(null, user);
  } catch (err) {
    done(err);
  }
}));

passport.serializeUser((user: any, done) => done(null, user._id));
passport.deserializeUser(async (id, done) => {
  try {
    const user = await (User as any).findById(id);
    done(null, user);
  } catch (err) {
    done(err);
  }
});

export default passport;
`;
}

export function getOauthRoutes(): string {
  return `import { Router } from 'express';
import passport from 'passport';
import jwt from 'jsonwebtoken';

const router = Router();

// Google OAuth
router.get('/google', passport.authenticate('google', { scope: ['profile', 'email'] }));
router.get('/google/callback',
  passport.authenticate('google', { session: false }),
  (req: any, res) => {
    const token = jwt.sign({ userId: req.user._id }, process.env.JWT_SECRET!, { expiresIn: '7d' });
    res.redirect(\`\${process.env.CLIENT_URL}/auth/success?token=\${token}\`);
  }
);

// GitHub OAuth
router.get('/github', passport.authenticate('github', { scope: ['user:email'] }));
router.get('/github/callback',
  passport.authenticate('github', { session: false }),
  (req: any, res) => {
    const token = jwt.sign({ userId: req.user._id }, process.env.JWT_SECRET!, { expiresIn: '7d' });
    res.redirect(\`\${process.env.CLIENT_URL}/auth/success?token=\${token}\`);
  }
);

export default router;
`;
}

// ─── RBAC MIDDLEWARE ─────────────────────────────────────────────────────────
export function getRbacMiddleware(): string {
  return `import { Request, Response, NextFunction } from 'express';

type Role = 'user' | 'admin' | 'moderator' | 'superadmin';

// Permission map
const permissions: Record<Role, string[]> = {
  user: ['read:own', 'update:own', 'delete:own'],
  moderator: ['read:own', 'read:any', 'update:own', 'update:any', 'delete:own'],
  admin: ['read:own', 'read:any', 'update:own', 'update:any', 'delete:own', 'delete:any', 'create:any'],
  superadmin: ['*'], // All permissions
};

export const hasPermission = (role: Role, permission: string): boolean => {
  const rolePermissions = permissions[role] || [];
  return rolePermissions.includes('*') || rolePermissions.includes(permission);
};

export const requireRole = (...allowedRoles: Role[]) => {
  return (req: any, res: Response, next: NextFunction) => {
    if (!req.userId) {
      return res.status(401).json({ success: false, message: 'Authentication required' });
    }
    if (!allowedRoles.includes(req.role as Role)) {
      return res.status(403).json({
        success: false,
        message: \`Access denied. Required roles: \${allowedRoles.join(', ')}\`
      });
    }
    next();
  };
};

export const requirePermission = (permission: string) => {
  return (req: any, res: Response, next: NextFunction) => {
    if (!req.userId) {
      return res.status(401).json({ success: false, message: 'Authentication required' });
    }
    if (!hasPermission(req.role as Role, permission)) {
      return res.status(403).json({
        success: false,
        message: \`Permission denied: \${permission}\`
      });
    }
    next();
  };
};
`;
}

// ─── FILE UPLOAD ─────────────────────────────────────────────────────────────
export function getFileUploadMiddleware(): string {
  return `import multer from 'multer';
import path from 'path';
import fs from 'fs';

// Ensure uploads directory exists
const uploadDir = 'uploads';
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => {
    const uniqueSuffix = \`\${Date.now()}-\${Math.round(Math.random() * 1e9)}\`;
    cb(null, \`\${file.fieldname}-\${uniqueSuffix}\${path.extname(file.originalname)}\`);
  },
});

const fileFilter = (req: any, file: Express.Multer.File, cb: multer.FileFilterCallback) => {
  const allowedTypes = /jpeg|jpg|png|gif|webp|pdf|doc|docx|xls|xlsx|mp4|mp3/;
  const extname = allowedTypes.test(path.extname(file.originalname).toLowerCase());
  const mimetype = allowedTypes.test(file.mimetype);
  if (extname && mimetype) cb(null, true);
  else cb(new Error('Invalid file type'));
};

export const upload = multer({
  storage,
  fileFilter,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB limit
});

export const uploadSingle = upload.single('file');
export const uploadMultiple = upload.array('files', 10);
export const uploadFields = upload.fields([
  { name: 'avatar', maxCount: 1 },
  { name: 'documents', maxCount: 5 },
]);
`;
}

export function getFileUploadController(): string {
  return `import { Request, Response } from 'express';
import fs from 'fs';
import path from 'path';

export const uploadSingleFile = async (req: Request, res: Response) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: 'No file uploaded' });
    }
    res.json({
      success: true,
      message: 'File uploaded successfully',
      file: {
        filename: req.file.filename,
        originalName: req.file.originalname,
        size: req.file.size,
        mimetype: req.file.mimetype,
        url: \`/uploads/\${req.file.filename}\`,
      },
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const uploadMultipleFiles = async (req: Request, res: Response) => {
  try {
    if (!req.files || (req.files as Express.Multer.File[]).length === 0) {
      return res.status(400).json({ success: false, message: 'No files uploaded' });
    }
    const files = (req.files as Express.Multer.File[]).map(f => ({
      filename: f.filename,
      originalName: f.originalname,
      size: f.size,
      url: \`/uploads/\${f.filename}\`,
    }));
    res.json({ success: true, files });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const deleteFile = async (req: Request, res: Response) => {
  try {
    const { filename } = req.params;
    const filePath = path.join('uploads', filename);
    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ success: false, message: 'File not found' });
    }
    fs.unlinkSync(filePath);
    res.json({ success: true, message: 'File deleted' });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message });
  }
};
`;
}

export function getFileUploadRoutes(): string {
  return `import { Router } from 'express';
import { uploadSingleFile, uploadMultipleFiles, deleteFile } from '../controllers/upload.controller';
import { uploadSingle, uploadMultiple } from '../middleware/upload.middleware';

const router = Router();

router.post('/single', uploadSingle, uploadSingleFile);
router.post('/multiple', uploadMultiple, uploadMultipleFiles);
router.delete('/:filename', deleteFile);

export default router;
`;
}

// ─── PUSH NOTIFICATIONS ──────────────────────────────────────────────────────
export function getPushNotificationService(): string {
  return `import webpush from 'web-push';

webpush.setVapidDetails(
  process.env.VAPID_EMAIL!,
  process.env.VAPID_PUBLIC_KEY!,
  process.env.VAPID_PRIVATE_KEY!
);

export interface PushSubscription {
  endpoint: string;
  keys: { p256dh: string; auth: string };
}

export const sendPushNotification = async (
  subscription: PushSubscription,
  payload: { title: string; body: string; icon?: string; url?: string }
): Promise<void> => {
  await webpush.sendNotification(subscription, JSON.stringify(payload));
};

export const sendBulkNotifications = async (
  subscriptions: PushSubscription[],
  payload: { title: string; body: string; icon?: string }
): Promise<void> => {
  const promises = subscriptions.map(sub =>
    sendPushNotification(sub, payload).catch(err => console.error('Push failed:', err))
  );
  await Promise.all(promises);
};

// Generate VAPID keys (run once)
export const generateVapidKeys = () => {
  const keys = webpush.generateVAPIDKeys();
  console.log('VAPID_PUBLIC_KEY:', keys.publicKey);
  console.log('VAPID_PRIVATE_KEY:', keys.privateKey);
  return keys;
};
`;
}

// ─── ELASTICSEARCH ───────────────────────────────────────────────────────────
export function getElasticsearchService(): string {
  return `import { Client } from '@elastic/elasticsearch';

const esClient = new Client({
  node: process.env.ELASTICSEARCH_URL || 'http://localhost:9200',
  auth: process.env.ELASTICSEARCH_USERNAME ? {
    username: process.env.ELASTICSEARCH_USERNAME,
    password: process.env.ELASTICSEARCH_PASSWORD!,
  } : undefined,
});

export const checkConnection = async (): Promise<void> => {
  try {
    await esClient.ping();
    console.log('✅ Elasticsearch connected');
  } catch (err) {
    console.error('❌ Elasticsearch connection failed:', err);
  }
};

export const createIndex = async (indexName: string, mappings: any): Promise<void> => {
  const exists = await esClient.indices.exists({ index: indexName });
  if (!exists) {
    await esClient.indices.create({ index: indexName, mappings });
  }
};

export const indexDocument = async (index: string, id: string, document: any): Promise<void> => {
  await esClient.index({ index, id, document });
};

export const searchDocuments = async (index: string, query: string, fields: string[]): Promise<any[]> => {
  const response = await esClient.search({
    index,
    query: {
      multi_match: {
        query,
        fields,
        fuzziness: 'AUTO',
      },
    },
  });
  return response.hits.hits.map((hit: any) => ({ id: hit._id, ...hit._source, score: hit._score }));
};

export const deleteDocument = async (index: string, id: string): Promise<void> => {
  await esClient.delete({ index, id });
};

export default esClient;
`;
}

// ─── AWS S3 CLOUD STORAGE ────────────────────────────────────────────────────
export function getS3Service(): string {
  return `import { S3Client, PutObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';

const s3Client = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
  },
});

export const uploadToS3 = async (fileName: string, fileBuffer: Buffer, mimeType: string) => {
  const command = new PutObjectCommand({
    Bucket: process.env.AWS_S3_BUCKET || '',
    Key: fileName,
    Body: fileBuffer,
    ContentType: mimeType,
  });
  await s3Client.send(command);
  return \`https://\${process.env.AWS_S3_BUCKET}.s3.\${process.env.AWS_REGION}.amazonaws.com/\${fileName}\`;
};

export const deleteFromS3 = async (fileName: string) => {
  const command = new DeleteObjectCommand({
    Bucket: process.env.AWS_S3_BUCKET || '',
    Key: fileName,
  });
  await s3Client.send(command);
};
`;
}

// ─── BULLMQ WORKER ───────────────────────────────────────────────────────────
export function getBullMQWorker(): string {
  return `import { Worker } from 'bullmq';

const worker = new Worker('default', async job => {
  console.log(\`Processing job \${job.id} of type \${job.name} with data:\`, job.data);
  // Add your background task logic here
}, {
  connection: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379'),
  }
});

worker.on('completed', job => {
  console.log(\`Job \${job.id} has completed!\`);
});

worker.on('failed', (job, err) => {
  console.error(\`Job \${job?.id} has failed with \${err.message}\`);
});

export default worker;
`;
}


// ─── SENTRY SETUP ────────────────────────────────────────────────────────────
export function getSentrySetup(config: ProjectConfig): string {
  return `import * as Sentry from '@sentry/node';

export const initSentry = (): void => {
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    environment: process.env.NODE_ENV || 'development',
    tracesSampleRate: process.env.NODE_ENV === 'production' ? 0.1 : 1.0,
    integrations: [
      new Sentry.Integrations.Http({ tracing: true }),
      new Sentry.Integrations.Express({ app: undefined }),
    ],
  });
  console.log('✅ Sentry initialized');
};

export const sentryRequestHandler = Sentry.Handlers.requestHandler();
export const sentryTracingHandler = Sentry.Handlers.tracingHandler();
export const sentryErrorHandler = Sentry.Handlers.errorHandler();

export const captureException = (error: Error, context?: Record<string, any>): void => {
  Sentry.withScope(scope => {
    if (context) scope.setExtras(context);
    Sentry.captureException(error);
  });
};
`;
}

// ─── JEST TEST FILES ─────────────────────────────────────────────────────────
export function getAuthTestTemplate(config: ProjectConfig): string {
  const ext = config.frontendLanguage === 'typescript' ? 'ts' : 'js';
  return `import request from 'supertest';
import app from '../server';

describe('Auth Routes', () => {
  const testUser = {
    name: 'Test User',
    email: 'test@example.com',
    password: 'Test1234!'
  };

  let authToken: string;

  describe('POST /api/auth/register', () => {
    it('should register a new user', async () => {
      const res = await request(app).post('/api/auth/register').send(testUser);
      expect(res.status).toBe(201);
      expect(res.body.success).toBe(true);
      expect(res.body.token).toBeDefined();
    });

    it('should fail with missing fields', async () => {
      const res = await request(app).post('/api/auth/register').send({ email: 'test@test.com' });
      expect(res.status).toBe(400);
      expect(res.body.success).toBe(false);
    });
  });

  describe('POST /api/auth/login', () => {
    it('should login with valid credentials', async () => {
      const res = await request(app).post('/api/auth/login').send({
        email: testUser.email,
        password: testUser.password
      });
      expect(res.status).toBe(200);
      expect(res.body.token).toBeDefined();
      authToken = res.body.token;
    });

    it('should fail with wrong password', async () => {
      const res = await request(app).post('/api/auth/login').send({
        email: testUser.email,
        password: 'wrongpassword'
      });
      expect(res.status).toBe(401);
    });
  });

  describe('GET /api/auth/profile', () => {
    it('should return profile with valid token', async () => {
      const res = await request(app)
        .get('/api/auth/profile')
        .set('Authorization', \`Bearer \${authToken}\`);
      expect(res.status).toBe(200);
      expect(res.body.user).toBeDefined();
    });

    it('should fail without token', async () => {
      const res = await request(app).get('/api/auth/profile');
      expect(res.status).toBe(401);
    });
  });
});
`;
}

export function getHealthTestTemplate(): string {
  return `import request from 'supertest';
import app from '../server';

describe('Health Check', () => {
  it('GET /health should return ok', async () => {
    const res = await request(app).get('/health');
    expect(res.status).toBe(200);
    expect(res.body.status).toBe('ok');
  });
});
`;
}

// ─── VUE TEMPLATE ────────────────────────────────────────────────────────────
export function getVueAppTemplate(config: ProjectConfig): string {
  const hasTailwind = config.cssFramework === 'Tailwind CSS';
  return `<template>
  <div${hasTailwind ? ' class="min-h-screen bg-gray-50 flex flex-col items-center justify-center"' : ''}>
    <h1${hasTailwind ? ' class="text-4xl font-bold text-gray-800"' : ''}>
      Welcome to {{ projectName }} 🧞
    </h1>
    <p${hasTailwind ? ' class="text-gray-500 mt-2"' : ''}>Generated by Navi</p>
    <button${hasTailwind ? ' class="mt-4 bg-blue-600 text-white px-6 py-2 rounded"' : ''} @click="count++">
      Count: {{ count }}
    </button>
  </div>
</template>

<script setup${config.frontendLanguage === 'typescript' ? ' lang="ts"' : ''}>
import { ref } from 'vue'

const projectName = '${config.projectName}'
const count = ref(0)
</script>
`;
}

export function getSvelteAppTemplate(config: ProjectConfig): string {
  const hasTailwind = config.cssFramework === 'Tailwind CSS';
  return `<script${config.frontendLanguage === 'typescript' ? ' lang="ts"' : ''}>
  let count = 0;
  const projectName = '${config.projectName}';
</script>

<main${hasTailwind ? ' class="min-h-screen flex flex-col items-center justify-center"' : ''}>
  <h1${hasTailwind ? ' class="text-4xl font-bold"' : ''}>{projectName} 🧞</h1>
  <p>Generated by Navi</p>
  <button on:click={() => count++}>Count: {count}</button>
</main>
${hasTailwind ? '' : `
<style>
  main { text-align: center; padding: 2rem; }
  h1 { font-size: 2rem; margin-bottom: 1rem; }
  button { padding: 0.5rem 1.5rem; cursor: pointer; }
</style>`}
`;
}

export function getAngularAppTemplate(config: ProjectConfig): string {
  return `import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: \`
    <div class="app-container">
      <h1>Welcome to {{ title }} 🧞</h1>
      <p>Generated by Navi</p>
      <button (click)="count++">Count: {{ count }}</button>
    </div>
  \`,
  styles: [\`
    .app-container { text-align: center; padding: 2rem; }
    h1 { font-size: 2rem; }
    button { padding: 0.5rem 1.5rem; cursor: pointer; }
  \`]
})
export class AppComponent {
  title = '${config.projectName}';
  count = 0;
}
`;
}

export function getVanillaHtmlTemplate(config: ProjectConfig): string {
  const hasTailwind = config.cssFramework === 'Tailwind CSS';
  const hasBootstrap = config.cssFramework === 'Bootstrap 5';
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${config.projectName}</title>
  ${hasTailwind ? '<script src="https://cdn.tailwindcss.com"></script>' : ''}
  ${hasBootstrap ? '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">' : ''}
  ${!hasTailwind && !hasBootstrap ? '<link rel="stylesheet" href="styles.css" />' : ''}
</head>
<body${hasTailwind ? ' class="min-h-screen flex items-center justify-center bg-gray-50"' : hasBootstrap ? ' class="d-flex align-items-center justify-content-center vh-100"' : ''}>
  <div${hasTailwind ? ' class="text-center"' : hasBootstrap ? ' class="text-center"' : ' class="container"'}>
    <h1${hasTailwind ? ' class="text-4xl font-bold text-gray-800 mb-4"' : hasBootstrap ? ' class="display-4 mb-3"' : ''}>Welcome to ${config.projectName} 🧞</h1>
    <p${hasTailwind ? ' class="text-gray-500"' : hasBootstrap ? ' class="lead"' : ''}>Generated by Navi</p>
    <button id="btn"${hasTailwind ? ' class="mt-4 bg-blue-600 text-white px-6 py-2 rounded hover:bg-blue-700"' : hasBootstrap ? ' class="btn btn-primary mt-3"' : ''}>
      Click me: <span id="count">0</span>
    </button>
  </div>
  <script>
    let count = 0;
    document.getElementById('btn').addEventListener('click', () => {
      count++;
      document.getElementById('count').textContent = count;
    });
  </script>
  ${hasBootstrap ? '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>' : ''}
</body>
</html>
`;
}

// ─── PLAYWRIGHT E2E TESTING ──────────────────────────────────────────────────
export function getPlaywrightConfig(config: ProjectConfig): string {
  return `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
    { name: 'webkit', use: { ...devices['Desktop Safari'] } },
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
});
`;
}

// ─── I18NEXT Setup ───────────────────────────────────────────────────────────
export function getI18nConfig(config: ProjectConfig): string {
  return `import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-http-backend';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    debug: process.env.NODE_ENV === 'development',
    interpolation: { escapeValue: false },
    resources: {
      en: {
        translation: {
          "welcome": "Welcome to \${config.projectName}",
        }
      },
      es: {
        translation: {
          "welcome": "Bienvenido a \${config.projectName}",
        }
      }
    }
  });

export default i18n;
`;
}

// ─── DARK/LIGHT THEME CSS VARIABLES ─────────────────────────────────────────
export function getThemeCssVariables(): string {
  return `:root {
  --color-primary: #6366f1;
  --color-primary-hover: #4f46e5;
  --color-secondary: #8b5cf6;
  --color-bg: #ffffff;
  --color-bg-secondary: #f9fafb;
  --color-text: #111827;
  --color-text-secondary: #6b7280;
  --color-border: #e5e7eb;
  --color-card: #ffffff;
  --color-shadow: rgba(0, 0, 0, 0.1);
  --radius: 0.5rem;
  --transition: all 0.2s ease;
}

[data-theme='dark'] {
  --color-bg: #0f172a;
  --color-bg-secondary: #1e293b;
  --color-text: #f1f5f9;
  --color-text-secondary: #94a3b8;
  --color-border: #334155;
  --color-card: #1e293b;
  --color-shadow: rgba(0, 0, 0, 0.4);
}

* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background-color: var(--color-bg);
  color: var(--color-text);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  transition: var(--transition);
}
`;
}

// ─── PAYMENT TEMPLATES ────────────────────────────────────────────────────────
export function getPaymentTemplate(config: ProjectConfig): string {
  if (config.features.includes('Payment Gateway (Razorpay)')) {
    return `import Razorpay from 'razorpay';
import { Request, Response } from 'express';
import crypto from 'crypto';

const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID!,
  key_secret: process.env.RAZORPAY_KEY_SECRET!,
});

export const createOrder = async (req: Request, res: Response) => {
  try {
    const { amount, currency = 'INR', receipt } = req.body;
    const order = await razorpay.orders.create({
      amount: amount * 100,
      currency,
      receipt: receipt || \`receipt_\${Date.now()}\`,
    });
    res.json({ success: true, order });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const verifyPayment = async (req: Request, res: Response) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;
    const sign = razorpay_order_id + '|' + razorpay_payment_id;
    const expectedSign = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET!)
      .update(sign.toString()).digest('hex');
    if (razorpay_signature === expectedSign) {
      res.json({ success: true, message: 'Payment verified successfully' });
    } else {
      res.status(400).json({ success: false, message: 'Invalid payment signature' });
    }
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message });
  }
};
`;
  }
  if (config.features.includes('Payment Gateway (Stripe)')) {
    return `import Stripe from 'stripe';
import { Request, Response } from 'express';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: '2023-10-16' });

export const createPaymentIntent = async (req: Request, res: Response) => {
  try {
    const { amount, currency = 'usd' } = req.body;
    const paymentIntent = await stripe.paymentIntents.create({
      amount: amount * 100,
      currency,
      automatic_payment_methods: { enabled: true },
    });
    res.json({ success: true, clientSecret: paymentIntent.client_secret });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const stripeWebhook = async (req: Request, res: Response) => {
  const sig = req.headers['stripe-signature']!;
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err: any) {
    return res.status(400).json({ message: \`Webhook Error: \${err.message}\` });
  }
  switch (event.type) {
    case 'payment_intent.succeeded': console.log('Payment succeeded:', event.data.object); break;
    case 'payment_intent.payment_failed': console.log('Payment failed:', event.data.object); break;
  }
  res.json({ received: true });
};
`;
  }
  return '';
}

// ─── EMAIL TEMPLATE ───────────────────────────────────────────────────────────
export function getEmailTemplate(): string {
  return `import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
});

export const sendEmail = async (to: string, subject: string, html: string): Promise<void> => {
  await transporter.sendMail({ from: \`"No Reply" <\${process.env.SMTP_USER}>\`, to, subject, html });
};

export const sendWelcomeEmail = async (to: string, name: string): Promise<void> => {
  await sendEmail(to, 'Welcome!', \`<h1>Welcome, \${name}! 🎉</h1><p>Your account is ready.</p>\`);
};

export const sendPasswordResetEmail = async (to: string, resetToken: string): Promise<void> => {
  const resetUrl = \`\${process.env.CLIENT_URL}/reset-password?token=\${resetToken}\`;
  await sendEmail(to, 'Password Reset', \`<h1>Reset Password</h1><a href="\${resetUrl}">Reset Password</a><p>Expires in 1 hour.</p>\`);
};

export const sendOtpEmail = async (to: string, otp: string): Promise<void> => {
  await sendEmail(to, 'Your OTP', \`<h1>Your OTP: <strong>\${otp}</strong></h1><p>Valid for 10 minutes.</p>\`);
};
`;
}

// ─── DOCKER ──────────────────────────────────────────────────────────────────
export function getDockerfileTemplate(config: ProjectConfig): string {
  return `# Navi Generated Dockerfile
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-alpine AS production
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
EXPOSE 5000
USER node
CMD ["node", "dist/server.js"]
`;
}

export function getDockerComposeTemplate(config: ProjectConfig): string {
  const hasMongoDb = config.database.includes('MongoDB');
  const hasPostgres = config.database.includes('PostgreSQL');
  const hasRedis = config.features.includes('Caching (Redis)');
  const hasElastic = config.features.includes('Search (Elasticsearch)');

  let compose = `version: '3.8'\n\nservices:\n  app:\n    build: .\n    ports:\n      - "5000:5000"\n    env_file:\n      - .env\n    depends_on:\n`;
  if (hasMongoDb) compose += `      - mongodb\n`;
  if (hasPostgres) compose += `      - postgres\n`;
  if (hasRedis) compose += `      - redis\n`;
  if (hasElastic) compose += `      - elasticsearch\n`;
  compose += `    restart: unless-stopped\n\n`;

  if (hasMongoDb) compose += `  mongodb:\n    image: mongo:6\n    ports:\n      - "27017:27017"\n    volumes:\n      - mongodb_data:/data/db\n    restart: unless-stopped\n\n`;
  if (hasPostgres) compose += `  postgres:\n    image: postgres:15\n    environment:\n      POSTGRES_DB: ${config.projectName.toLowerCase()}\n      POSTGRES_USER: postgres\n      POSTGRES_PASSWORD: password\n    ports:\n      - "5432:5432"\n    volumes:\n      - postgres_data:/var/lib/postgresql/data\n    restart: unless-stopped\n\n`;
  if (hasRedis) compose += `  redis:\n    image: redis:7-alpine\n    ports:\n      - "6379:6379"\n    command: redis-server --requirepass \${REDIS_PASSWORD:-}\n    restart: unless-stopped\n\n`;
  if (hasElastic) compose += `  elasticsearch:\n    image: elasticsearch:8.11.0\n    environment:\n      - discovery.type=single-node\n      - xpack.security.enabled=false\n    ports:\n      - "9200:9200"\n    volumes:\n      - elastic_data:/usr/share/elasticsearch/data\n    restart: unless-stopped\n\n`;

  compose += `volumes:\n`;
  if (hasMongoDb) compose += `  mongodb_data:\n`;
  if (hasPostgres) compose += `  postgres_data:\n`;
  if (hasElastic) compose += `  elastic_data:\n`;

  return compose;
}

// ─── CI/CD ───────────────────────────────────────────────────────────────────
export function getGithubActionsTemplate(config: ProjectConfig): string {
  return `name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      ${config.features.includes('Testing (Jest)') ? '- run: npm test -- --coverage' : ''}
      ${config.features.includes('ESLint + Prettier') ? '- run: npm run lint' : ''}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      ${config.deployTarget === 'Vercel' ? '- uses: amondnet/vercel-action@v25\n        with:\n          vercel-token: ${{ secrets.VERCEL_TOKEN }}\n          vercel-org-id: ${{ secrets.ORG_ID }}\n          vercel-project-id: ${{ secrets.PROJECT_ID }}' : '# Add your deployment steps here'}
`;
}
