import { ProjectConfig } from '../types';

export function getPhpIndex(config: ProjectConfig): string {
  const { backendFramework } = config;

  if (backendFramework === 'Laravel') {
    return `<?php
    
// Laravel requires Composer and its own CLI structure.
// Run: composer create-project laravel/laravel ${config.projectName}
echo json_encode(['status' => 'ok', 'message' => '🧭 Navi Laravel project generated via instructions!']);
`;
  }

  if (backendFramework === 'Symfony') {
    return `<?php

// Symfony requires its own CLI.
// Run: symfony new ${config.projectName} --version="7.0.*" --webapp
echo json_encode(['status' => 'ok', 'message' => '🧭 Navi Symfony project generated via instructions!']);
`;
  }
  
  // Standard PHP
  return `<?php
header('Content-Type: application/json');

if ($_SERVER['REQUEST_URI'] === '/health') {
    echo json_encode(['status' => 'ok', 'message' => '🧭 Navi PHP is running!']);
    exit;
}

echo "Navi PHP Backend";
`;
}

export function getPhpComposerJson(config: ProjectConfig): string {
  return `{
    "name": "amanblaze/${config.projectName.toLowerCase().replace(/\\s+/g, '-')}",
    "description": "Generated by Navi 🧭",
    "type": "project",
    "require": {
        "php": "^8.1"
    },
    "license": "MIT"
}
`;
}
